create database customer_behaviour;
use customer_behaviour;
select * from customer;
select * from customer limit 5;
-- Q1. What is the total revenue generated by male vs female customer?
select gender, sum(purchase_amount) as total_revenue
from customer
group by gender;

-- Q2. which customers used a discount but still spent more than the average purchase amount?
select customer_id, sum(purchase_amount) as total_spent
from customer
where discount_applied = "Yes"
group by customer_id
having sum(purchase_amount)> (select avg(purchase_amount) from customer);

-- Q3. which are the top 5 products with the highest average review rating?
select item_purchased, avg(purchase_amount) as avg_rating
from customer
group by item_purchased
order by avg_rating desc
limit 5;

-- Q4. Compare the average purchase amounts between standard and Express Shipping.
select * from customer limit 5;
select shipping_type, avg(purchase_amount) as avg_purchase
from customer
group by shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend the total revenue between subscribers and non-subscribers.
select subscription_status, avg(purchase_amount) as avg_purchase, sum(purchase_amount) as total_purchase
from customer
group by subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?;
select item_purchased, avg(discount_applied = 'Yes') * 100 as percentage_of_purchases_with_discount
from customer
group by item_purchased
order by percentage_of_purchases_with_discount desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
select
	case 
		when previous_purchases = 0 then 'NEW'
        when previous_purchases between 1 AND 5 then 'Returning'
        else 'Loyal'
        End as 'customer_segment',
        count(*) as customer_count
        from 
        customer
        group by customer_segment;
-- Q8. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select * from customer limit 5;
select subscription_status,
count(*) as customer_count,
ROUND(count(*) * 100.0 / sum(count(*)) over(), 2) as percentage
from customer
where previous_purchases >5
group by subscription_status;

-- Q9. What is the revenue contribution if each age group?
select 
case 
	when age < 20 then 'UNDER 20'
	when age between 20 and 29 then '20-29'
    when age between 30 and 39 then '30-39'
    when age between 40 and 49 then '40-49'
    when age between 50 and 59 then '50-59'
    else 'else 60 over'
    end as age_group,
    sum(purchase_amount) as total_revenue,
    round(sum(purchase_amount)* 100/ (select sum(purchase_amount) from customer), 2) as revenue_percentage
    from customer
    group by
    case 
	when age < 20 then 'UNDER 20'
	when age between 20 and 29 then '20-29'
    when age between 30 and 39 then '30-39'
    when age between 40 and 49 then '40-49'
    when age between 50 and 59 then '50-59'
    else 'else 60 over'
    end
    order by age_group;
  
    select age_group,
    sum(purchase_amount) as total_revenue
    from customer
    group by age_group 
    order by total_revenue desc;
    -- what are the top 3 most purchasd products within each category?


SELECT category, item_purchased, total, rank_in_category
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(*) DESC
        ) AS rank_in_category
    FROM customer
    GROUP BY category, item_purchased
) AS ranked_products
WHERE rank_in_category <= 3
ORDER BY category, rank_in_category;

    